openapi: 3.2.0
info:
  title: Opendata ATM API
  description: Open Data API V2.2 for Danske Bank
  version: 4.3.3
  x-db-template-version: 1.0.0
servers:
- description: prod Environment
  url: https://obp-data.danskebank.com/v2.2
tags:
- name: ATM
paths:
  /atms:
    get:
      tags:
      - ATM
      summary: Gets a list of all ATM objects
      description: Gets a list of all ATM objects
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/AtmsResponse'
              example:
                meta:
                  LastUpdated: 2025-10-10T16:00:00.318+0530
                  TotalResults: 70
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: Danske Bank
                  ATM:
                  - Identification: '12345678'
                    SupportedLanguages:
                    - eng
                    ATMServices:
                    - Balance
                    - CashWithdrawal
                    Accessibility:
                    - WheelchairAccess
                    SupportedCurrencies:
                    - GBP
                    MinimumPossibleAmount: '10'
                    Note:
                    - Danske note
                    OtherATMServices:
                    - Name: Cash Deposits
                      Description: Danske description
                    Branch:
                      Identification: '123456'
                    Location:
                      LocationCategory:
                      - BranchInternal
                      Site:
                        Name: Danske Site
                      PostalAddress:
                        BuildingNumber: '1'
                        StreetName: Street 1
                        TownName: Town 1
                        CountrySubDivision:
                        - NIR
                        Country: GB
                        PostCode: '123456'
                        GeoLocation:
                          GeographicCoordinates:
                            Latitude: '54.00000'
                            Longitude: '-5.00000'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve ATMs
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
    head:
      tags:
      - ATM
      summary: Gets header information on the current set of ATM data
      description: Gets header information on the current set of ATM data
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/AtmsResponse'
              example:
                meta:
                  LastUpdated: 2025-10-10T16:00:00.318+0530
                  TotalResults: 70
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: Danske Bank
                  ATM:
                  - Identification: '12345678'
                    SupportedLanguages:
                    - eng
                    ATMServices:
                    - Balance
                    - CashWithdrawal
                    Accessibility:
                    - WheelchairAccess
                    SupportedCurrencies:
                    - GBP
                    MinimumPossibleAmount: '10'
                    Note:
                    - Danske note
                    OtherATMServices:
                    - Name: Cash Deposits
                      Description: Danske description
                    Branch:
                      Identification: '123456'
                    Location:
                      LocationCategory:
                      - BranchInternal
                      Site:
                        Name: Danske Site
                      PostalAddress:
                        BuildingNumber: '1'
                        StreetName: Street 1
                        TownName: Town 1
                        CountrySubDivision:
                        - NIR
                        Country: GB
                        PostCode: '123456'
                        GeoLocation:
                          GeographicCoordinates:
                            Latitude: '54.00000'
                            Longitude: '-5.00000'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve ATMs
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
components:
  schemas:
    Meta:
      type: object
      properties:
        LastUpdated:
          type: string
          format: date-time
        TotalResults:
          type: integer
        Agreement:
          type: string
        License:
          type: string
          format: uri
        TermsOfUse:
          type: string
          format: uri
    AtmsResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            type: object
            properties:
              BrandName:
                type: string
              ATM:
                type: array
                items:
                  type: object
                  properties:
                    Identification:
                      type: string
                    SupportedLanguages:
                      type: array
                      items:
                        type: string
                    ATMServices:
                      type: array
                      items:
                        type: string
                    Accessibility:
                      type: array
                      items:
                        type: string
                    SupportedCurrencies:
                      type: array
                      items:
                        type: string
                    MinimumPossibleAmount:
                      type: string
                    Note:
                      type: array
                      items:
                        type: string
                    OtherATMServices:
                      type: array
                      items:
                        type: object
                        properties:
                          Name:
                            type: string
                          Description:
                            type: string
                    Branch:
                      type: object
                      properties:
                        Identification:
                          type: string
                    Location:
                      type: object
                      properties:
                        LocationCategory:
                          type: array
                          items:
                            type: string
                        Site:
                          type: object
                          properties:
                            Name:
                              type: string
                        PostalAddress:
                          type: object
                          properties:
                            BuildingNumber:
                              type: string
                            StreetName:
                              type: string
                            TownName:
                              type: string
                            CountrySubDivision:
                              type: array
                              items:
                                type: string
                            Country:
                              type: string
                            PostCode:
                              type: string
                            GeoLocation:
                              type: object
                              properties:
                                GeographicCoordinates:
                                  type: object
                                  properties:
                                    Latitude:
                                      type: string
                                    Longitude:
                                      type: string
      required:
      - meta
      - data
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        detail:
          type: string
      required:
      - status
      - code
      - message
      - detail
  securitySchemes:
    clientIdHeader:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
    clientSecretHeader:
      type: apiKey
      description: BC2702Z
      name: X-IBM-Client-Secret
      in: header
