openapi: 3.2.0
info:
  title: Opendata Branch API
  description: Open Data API V2.2 for Danske Bank
  version: 4.3.3
  x-db-template-version: 1.0.0
servers:
- description: prod Environment
  url: https://obp-data.danskebank.com/v2.2
tags:
- name: Branch
paths:
  /branches:
    get:
      tags:
      - Branch
      summary: Gets a list of all Branch objects
      description: Gets a list of all Branch objects
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/BranchesResponse'
              example:
                meta:
                  LastUpdated: 2025-08-07T16:18:24.508+0530
                  TotalResults: 2
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: DanskeBank
                  Branch:
                  - Identification: '950611'
                    SequenceNumber: '0'
                    Name: Belfast Business Centre
                    Type: Physical
                    CustomerSegment:
                    - Business
                    ServiceAndFacility:
                    - InternalATM
                    Accessibility:
                    - AutomaticDoors
                    Note: Belfast Business Centre
                    Availability:
                      StandardAvailability:
                        Day:
                        - Name: Monday
                          Notes: No counter service - visit by appointment only
                          OpeningHours:
                          - OpeningTime: 09:30
                            ClosingTime: '15:00'
                    PostalAddress:
                      BuildingNumber: P.O. Box 183
                      StreetName: Donegall Square West
                      TownName: Belfast
                      CountrySubDivision:
                      - NIR
                      Country: GB
                      PostCode: BT1 6JS
                      GeoLocation:
                        GeographicCoordinates:
                          Latitude: '54.5962'
                          Longitude: '-5.9317'
                    SortCode:
                    - '950611'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve branches
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
    head:
      tags:
      - Branch
      summary: Gets header information on the current set of Branch data
      description: Gets header information on the current set of Branch data
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/BranchesResponse'
              example:
                meta:
                  LastUpdated: 2025-08-07T16:18:24.508+0530
                  TotalResults: 2
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: DanskeBank
                  Branch:
                  - Identification: '950611'
                    SequenceNumber: '0'
                    Name: Belfast Business Centre
                    Type: Physical
                    CustomerSegment:
                    - Business
                    ServiceAndFacility:
                    - InternalATM
                    Accessibility:
                    - AutomaticDoors
                    Note: Belfast Business Centre
                    Availability:
                      StandardAvailability:
                        Day:
                        - Name: Monday
                          Notes: No counter service - visit by appointment only
                          OpeningHours:
                          - OpeningTime: 09:30
                            ClosingTime: '15:00'
                    PostalAddress:
                      BuildingNumber: P.O. Box 183
                      StreetName: Donegall Square West
                      TownName: Belfast
                      CountrySubDivision:
                      - NIR
                      Country: GB
                      PostCode: BT1 6JS
                      GeoLocation:
                        GeographicCoordinates:
                          Latitude: '54.5962'
                          Longitude: '-5.9317'
                    SortCode:
                    - '950611'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve branches
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
components:
  schemas:
    Meta:
      type: object
      properties:
        LastUpdated:
          type: string
          format: date-time
        TotalResults:
          type: integer
        Agreement:
          type: string
        License:
          type: string
          format: uri
        TermsOfUse:
          type: string
          format: uri
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        detail:
          type: string
      required:
      - status
      - code
      - message
      - detail
    BranchesResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            type: object
            properties:
              BrandName:
                type: string
              Branch:
                type: array
                items:
                  type: object
                  properties:
                    Identification:
                      type: string
                    SequenceNumber:
                      type: string
                    Name:
                      type: string
                    Type:
                      type: string
                    CustomerSegment:
                      type: array
                      items:
                        type: string
                    ServiceAndFacility:
                      type: array
                      items:
                        type: string
                    Accessibility:
                      type: array
                      items:
                        type: string
                    Note:
                      type: string
                    OtherServiceAndFacility:
                      type:
                      - array
                      - 'null'
                      items:
                        type: object
                        properties:
                          Code:
                            type: string
                          Name:
                            type: string
                          Description:
                            type: string
                    Availability:
                      type: object
                      properties:
                        StandardAvailability:
                          type: object
                          properties:
                            Day:
                              type: array
                              items:
                                type: object
                                properties:
                                  Name:
                                    type: string
                                  Notes:
                                    type: string
                                  OpeningHours:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        OpeningTime:
                                          type: string
                                        ClosingTime:
                                          type: string
                    PostalAddress:
                      type: object
                      properties:
                        BuildingNumber:
                          type: string
                        StreetName:
                          type: string
                        TownName:
                          type: string
                        CountrySubDivision:
                          type: array
                          items:
                            type: string
                        Country:
                          type: string
                        PostCode:
                          type: string
                        GeoLocation:
                          type: object
                          properties:
                            GeographicCoordinates:
                              type: object
                              properties:
                                Latitude:
                                  type: string
                                Longitude:
                                  type: string
                    SortCode:
                      type: array
                      items:
                        type: string
      required:
      - meta
      - data
  securitySchemes:
    clientIdHeader:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
    clientSecretHeader:
      type: apiKey
      description: BC2702Z
      name: X-IBM-Client-Secret
      in: header
