openapi: 3.2.0
info:
  title: Opendata PCA API
  description: Open Data API V2.2 for Danske Bank
  version: 4.3.3
  x-db-template-version: 1.0.0
servers:
- description: prod Environment
  url: https://obp-data.danskebank.com/v2.2
tags:
- name: PCA
paths:
  /personal-current-accounts:
    get:
      tags:
      - PCA
      summary: Gets a list of all Personal Current Account objects
      description: Gets a list of all Personal Current Account objects
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/PersonalCurrentAccountsResponse'
              example:
                meta:
                  LastUpdated: '2025-10-09T16:00:51.831Z'
                  TotalResults: 5
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: DanskeBank
                  PCA:
                  - Name: Danske Reward
                    Identification: 58S
                    Segment:
                    - Reward
                    OnSaleIndicator: true
                    PCAMarketingState:
                    - Identification: 58S
                      MarketingState: Regular
                      FirstMarketedDate: '1900-01-01'
                      LastMarketedDate: '9999-12-31'
                      Overdraft:
                        TcsAndCsURL: http://www.danskebank.co.uk/SiteCollectionDocuments/tcs-personal-banking.pdf
                        OverdraftTierBandSet:
                        - TierBandMethod: Whole
                          OverdraftType: OnDemand
                          Identification: 58S
                          AuthorisedIndicator: true
                          OverdraftTierBand:
                          - Identification: 58S
                            TierValueMin: '0'
                            OverdraftInterestChargingCoverage: Whole
                            EAR: '29.90'
                            Notes:
                            - There is an arranged overdraft set-up fee at 1% of any amount over £10k
                          OverdraftFeesCharges:
                          - OverdraftFeeChargeDetail:
                            - FeeType: UnauthorisedUnpaidTrans
                              FeeAmount: '1.50'
                              ApplicationFrequency: Monthly
                              CalculationFrequency: PerTransaction
                              OverdraftFeeChargeCap:
                                FeeType:
                                - UnauthorisedUnpaidTrans
                                MinMaxType: Maximum
                                FeeCapAmount: '4.50'
                                CappingPeriod: Month
                      Eligibility:
                        OtherEligibility:
                        - Name: Ownership
                          Description: Customers are limited to one sole and/or one joint account
                          Type: Other
                        AgeEligibility:
                          MinimumAge: 18
                        ResidencyEligibility:
                          ResidencyIncluded:
                          - NI
                        CreditCheck:
                          ScoringType: Hard
                        IDVerificationCheck:
                          URL: https://danskebank.co.uk/personal/become-a-customer
                          Notes:
                          - Experian KYC and Identity Authenticate by Experian used for identity verification
                      FeaturesAndBenefits:
                        FeatureBenefitGroup:
                        - Name: Reward
                          Type: Cashback
                          BenefitGroupNominalValue: '5'
                          ApplicationFrequency: Monthly
                          CalculationFrequency: Monthly
                          FeatureBenefitEligibility:
                          - Name: Reward
                            Type: MinimumDeposit
                            Amount: '1000'
                            Period: Month
                          - Name: Reward
                            Type: Other
                            Textual: Customers must receive digital statements for the account
                            Period: Month
                        FeatureBenefitItem:
                        - Type: AccountManagement
                          Textual: Lodge and withdraw money at any of our branches across Northern Ireland
                        Card:
                        - Type: DebitCard
                          Scheme: MasterCard
                          ContactlessIndicator: true
                        MobileWallet:
                        - Type: ApplePay
                        - Type: GooglePay
                      OtherFeesCharges:
                        FeeChargeDetail:
                        - FeeCategory: PaymentScheme
                          FeeType: FPSInBranch
                          FeeAmount: '10'
                          ApplicationFrequency: PerTransaction
                          CalculationFrequency: PerTransaction
                      CoreProduct:
                        ProductURL: https://danskebank.co.uk/personal/products/current-accounts/danske-reward
                        ProductDescription: Danske Reward is an everyday current account that gives you a reward every month for banking with Danske Bank
                        TcsAndCsURL: http://www.danskebank.co.uk/SiteCollectionDocuments/tcs-personal-banking.pdf
                        SalesAccessChannels:
                        - Branch
                        - Online
                        - CallCentre
                        ServicingAccessChannels:
                        - Branch
                        - Online
                        - MobileBankingApp
                        MonthlyMaximumCharge: '4.50'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve personal current accounts
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
    head:
      tags:
      - PCA
      summary: Gets header information on the current set of Personal Current Account data
      description: Gets header information on the current set of Personal Current Account data
      parameters:
      - name: If-Modified-Since
        in: query
        schema:
          type: string
      - name: If-None-Match
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/PersonalCurrentAccountsResponse'
              example:
                meta:
                  LastUpdated: '2025-10-09T16:00:51.831Z'
                  TotalResults: 5
                  Agreement: Use of the APIs and any related data will be subject to the terms of the Open Licence and subject to terms and conditions
                  License: https://www.openbanking.org.uk/open-licence
                  TermsOfUse: https://www.openbanking.org.uk/terms-conditions
                data:
                - BrandName: DanskeBank
                  PCA:
                  - Name: Danske Reward
                    Identification: 58S
                    Segment:
                    - Reward
                    OnSaleIndicator: true
                    PCAMarketingState:
                    - Identification: 58S
                      MarketingState: Regular
                      FirstMarketedDate: '1900-01-01'
                      LastMarketedDate: '9999-12-31'
                      Overdraft:
                        TcsAndCsURL: http://www.danskebank.co.uk/SiteCollectionDocuments/tcs-personal-banking.pdf
                        OverdraftTierBandSet:
                        - TierBandMethod: Whole
                          OverdraftType: OnDemand
                          Identification: 58S
                          AuthorisedIndicator: true
                          OverdraftTierBand:
                          - Identification: 58S
                            TierValueMin: '0'
                            OverdraftInterestChargingCoverage: Whole
                            EAR: '29.90'
                            Notes:
                            - There is an arranged overdraft set-up fee at 1% of any amount over £10k
                          OverdraftFeesCharges:
                          - OverdraftFeeChargeDetail:
                            - FeeType: UnauthorisedUnpaidTrans
                              FeeAmount: '1.50'
                              ApplicationFrequency: Monthly
                              CalculationFrequency: PerTransaction
                              OverdraftFeeChargeCap:
                                FeeType:
                                - UnauthorisedUnpaidTrans
                                MinMaxType: Maximum
                                FeeCapAmount: '4.50'
                                CappingPeriod: Month
                      Eligibility:
                        OtherEligibility:
                        - Name: Ownership
                          Description: Customers are limited to one sole and/or one joint account
                          Type: Other
                        AgeEligibility:
                          MinimumAge: 18
                        ResidencyEligibility:
                          ResidencyIncluded:
                          - NI
                        CreditCheck:
                          ScoringType: Hard
                        IDVerificationCheck:
                          URL: https://danskebank.co.uk/personal/become-a-customer
                          Notes:
                          - Experian KYC and Identity Authenticate by Experian used for identity verification
                      FeaturesAndBenefits:
                        FeatureBenefitGroup:
                        - Name: Reward
                          Type: Cashback
                          BenefitGroupNominalValue: '5'
                          ApplicationFrequency: Monthly
                          CalculationFrequency: Monthly
                          FeatureBenefitEligibility:
                          - Name: Reward
                            Type: MinimumDeposit
                            Amount: '1000'
                            Period: Month
                          - Name: Reward
                            Type: Other
                            Textual: Customers must receive digital statements for the account
                            Period: Month
                        FeatureBenefitItem:
                        - Type: AccountManagement
                          Textual: Lodge and withdraw money at any of our branches across Northern Ireland
                        Card:
                        - Type: DebitCard
                          Scheme: MasterCard
                          ContactlessIndicator: true
                        MobileWallet:
                        - Type: ApplePay
                        - Type: GooglePay
                      OtherFeesCharges:
                        FeeChargeDetail:
                        - FeeCategory: PaymentScheme
                          FeeType: FPSInBranch
                          FeeAmount: '10'
                          ApplicationFrequency: PerTransaction
                          CalculationFrequency: PerTransaction
                      CoreProduct:
                        ProductURL: https://danskebank.co.uk/personal/products/current-accounts/danske-reward
                        ProductDescription: Danske Reward is an everyday current account that gives you a reward every month for banking with Danske Bank
                        TcsAndCsURL: http://www.danskebank.co.uk/SiteCollectionDocuments/tcs-personal-banking.pdf
                        SalesAccessChannels:
                        - Branch
                        - Online
                        - CallCentre
                        ServicingAccessChannels:
                        - Branch
                        - Online
                        - MobileBankingApp
                        MonthlyMaximumCharge: '4.50'
        '400':
          description: Bad request
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 400
                message: Bad request
                detail: You have sent a request which could not be understood
        '408':
          description: Client timeout
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 408
                message: Client timeout
                detail: Your client has failed to submit a request, and a timeout has occurred
        '429':
          description: Too many requests
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 429
                message: Too many requests
                detail: You have requested this resource too often, slow down
        '500':
          description: Internal Server Error
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 500
                message: Internal Server Error
                detail: Failed to retrieve personal current accounts
        '503':
          description: Service temporarily unavailable
          content:
            application/prs.openbanking.opendata.v2.2+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                code: 503
                message: Service temporarily unavailable
                detail: The service is temporarily unavailable
components:
  schemas:
    Meta:
      type: object
      properties:
        LastUpdated:
          type: string
          format: date-time
        TotalResults:
          type: integer
        Agreement:
          type: string
        License:
          type: string
          format: uri
        TermsOfUse:
          type: string
          format: uri
    PersonalCurrentAccountsResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            type: object
            properties:
              BrandName:
                type: string
              PCA:
                type: array
                items:
                  type: object
                  properties:
                    Name:
                      type: string
                    Identification:
                      type: string
                    Segment:
                      type: array
                      items:
                        type: string
                    OnSaleIndicator:
                      type: boolean
                    PCAMarketingState:
                      type: array
                      items:
                        type: object
                        properties:
                          Identification:
                            type: string
                          MarketingState:
                            type: string
                          FirstMarketedDate:
                            type: string
                          LastMarketedDate:
                            type: string
                          Overdraft:
                            type: object
                            properties:
                              TcsAndCsURL:
                                type: string
                                format: uri
                              OverdraftTierBandSet:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    TierBandMethod:
                                      type: string
                                    OverdraftType:
                                      type: string
                                    Identification:
                                      type: string
                                    AuthorisedIndicator:
                                      type: boolean
                                    BufferAmount:
                                      type:
                                      - string
                                      - 'null'
                                    OverdraftTierBand:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          Identification:
                                            type: string
                                          TierValueMin:
                                            type: string
                                          TierValueMax:
                                            type:
                                            - string
                                            - 'null'
                                          OverdraftInterestChargingCoverage:
                                            type: string
                                          BankGuaranteedIndicator:
                                            type:
                                            - boolean
                                            - 'null'
                                          EAR:
                                            type: string
                                          Notes:
                                            type: array
                                            items:
                                              type: string
                                          OverdraftFeesCharges:
                                            type:
                                            - array
                                            - 'null'
                                            items:
                                              type: object
                                              properties:
                                                OverdraftFeeChargeDetail:
                                                  type:
                                                  - array
                                                  - 'null'
                                                  items:
                                                    type: object
                                                    properties:
                                                      FeeType:
                                                        type:
                                                        - string
                                                        - 'null'
                                                      FeeAmount:
                                                        type:
                                                        - string
                                                        - 'null'
                                                      ApplicationFrequency:
                                                        type:
                                                        - string
                                                        - 'null'
                                                      CalculationFrequency:
                                                        type:
                                                        - string
                                                        - 'null'
                                                      OverdraftFeeChargeCap:
                                                        type: object
                                                        properties:
                                                          FeeType:
                                                            type: array
                                                            items:
                                                              type: string
                                                          MinMaxType:
                                                            type: string
                                                          FeeCapAmount:
                                                            type: string
                                                          CappingPeriod:
                                                            type: string
                                    OverdraftFeesCharges:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          OverdraftFeeChargeDetail:
                                            type: array
                                            items:
                                              type: object
                                              properties:
                                                FeeType:
                                                  type: string
                                                FeeAmount:
                                                  type: string
                                                ApplicationFrequency:
                                                  type: string
                                                CalculationFrequency:
                                                  type: string
                                                OverdraftFeeChargeCap:
                                                  type: object
                                                  properties:
                                                    FeeType:
                                                      type: array
                                                      items:
                                                        type: string
                                                    MinMaxType:
                                                      type: string
                                                    FeeCapAmount:
                                                      type: string
                                                    CappingPeriod:
                                                      type: string
                          Eligibility:
                            type: object
                            properties:
                              OtherEligibility:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    Name:
                                      type: string
                                    Description:
                                      type: string
                                    Type:
                                      type: string
                              AgeEligibility:
                                type: object
                                properties:
                                  MinimumAge:
                                    type: number
                                  MaximumAge:
                                    type:
                                    - number
                                    - 'null'
                              ResidencyEligibility:
                                type: object
                                properties:
                                  ResidencyType:
                                    type:
                                    - string
                                    - 'null'
                                  ResidencyIncluded:
                                    type: array
                                    items:
                                      type: string
                              CreditCheck:
                                type: object
                                properties:
                                  ScoringType:
                                    type: string
                              IDVerificationCheck:
                                type: object
                                properties:
                                  URL:
                                    type: string
                                    format: uri
                                  Notes:
                                    type:
                                    - array
                                    - 'null'
                                    items:
                                      type: string
                          FeaturesAndBenefits:
                            type:
                            - object
                            - 'null'
                            properties:
                              FeatureBenefitGroup:
                                type:
                                - array
                                - 'null'
                                items:
                                  type: object
                                  properties:
                                    Name:
                                      type:
                                      - string
                                      - 'null'
                                    Type:
                                      type:
                                      - string
                                      - 'null'
                                    ApplicationFrequency:
                                      type:
                                      - string
                                      - 'null'
                                    CalculationFrequency:
                                      type:
                                      - string
                                      - 'null'
                                    FeatureBenefitItem:
                                      type:
                                      - array
                                      - 'null'
                                      items:
                                        type: object
                                        properties:
                                          Identification:
                                            type:
                                            - string
                                            - 'null'
                                          Type:
                                            type:
                                            - string
                                            - 'null'
                                          Textual:
                                            type:
                                            - string
                                            - 'null'
                              FeatureBenefitItem:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    Type:
                                      type: string
                                    Name:
                                      type:
                                      - string
                                      - 'null'
                                    Textual:
                                      type: string
                              Card:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    Type:
                                      type: string
                                    Scheme:
                                      type: string
                                    ContactlessIndicator:
                                      type: boolean
                              MobileWallet:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    Type:
                                      type: string
                                    Notes:
                                      type:
                                      - array
                                      - 'null'
                                      items:
                                        type: string
                          OtherFeesCharges:
                            type: object
                            properties:
                              FeeChargeDetail:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    FeeCategory:
                                      type: string
                                    FeeType:
                                      type: string
                                    FeeAmount:
                                      type: string
                                    FeeRate:
                                      type:
                                      - string
                                      - 'null'
                                    ApplicationFrequency:
                                      type: string
                                    CalculationFrequency:
                                      type: string
                                    Notes:
                                      type:
                                      - array
                                      - 'null'
                                      items:
                                        type: string
                          CoreProduct:
                            type: object
                            properties:
                              ProductURL:
                                type: string
                                format: uri
                              ProductDescription:
                                type: string
                              TcsAndCsURL:
                                type: string
                                format: uri
                              SalesAccessChannels:
                                type: array
                                items:
                                  type: string
                              ServicingAccessChannels:
                                type: array
                                items:
                                  type: string
                              MonthlyMaximumCharge:
                                type: string
      required:
      - meta
      - data
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        detail:
          type: string
      required:
      - status
      - code
      - message
      - detail
  securitySchemes:
    clientIdHeader:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
    clientSecretHeader:
      type: apiKey
      description: BC2702Z
      name: X-IBM-Client-Secret
      in: header
